### PR TITLE
usb: update manufacturer HID descriptor to bitbox.swiss

### PR DESCRIPTION
**Pull request by Beerosagos**

### CODE REVIEW

**Review by benma — COMMENTED** [review]
Thanks. As usual, please add a CHANGELOG entry (this time for both firmware and bootloader).

Also please bump the bootloader version to v1.0.7.

**Comment by Beerosagos** [comment]
> Thanks. As usual, please add a CHANGELOG entry (this time for both firmware and bootloader).
> 
> Also please bump the bootloader version to v1.0.7.

I always forget about CHANGELOG :see_no_evil:

**Review by NickeZ — APPROVED** [review]
utAck

**Comment by Beerosagos** [comment]
@benma done, PTAL

**Review by benma — APPROVED** [review]
tACK firmware

**Pull request merged**
