### PR TITLE
Update to CMSIS 6.1

### PR DESCRIPTION
**Pull request by NickeZ**
Upgrade CMSIS to 6.1.

This PR also solves the `clang-tidy`, `vfpcc`, issue. I guess the headers are changed to work better with clang.

bootloader.bin and firmware.bin do not change after this upgrade.

### CODE REVIEW

**Comment by NickeZ** [comment]
Replaces https://github.com/BitBoxSwiss/bitbox02-firmware/pull/1289

**Review by benma — APPROVED** [review]
I tested that the firmware binary does not change with this.

Would be nice if you could add info about how exactly you upgraded (where from, any modifications that were needed, ...) in the commit msg.

**Comment by NickeZ** [comment]
> I tested that the firmware binary does not change with this.
> 
> Would be nice if you could add info about how exactly you upgraded (where from, any modifications that were needed, ...) in the commit msg.

I wrote a more elaborate commit msg. Will wait for CI before merging.

**Comment by benma** [comment]
> > I tested that the firmware binary does not change with this.
> > Would be nice if you could add info about how exactly you upgraded (where from, any modifications that were needed, ...) in the commit msg.
> 
> I wrote a more elaborate commit msg. Will wait for CI before merging.

Perfect, thanks

**Pull request merged**
