### PR TITLE
sdcard: improvement on reinsertion fix

### PR DESCRIPTION
**Pull request by asi345**

### CODE REVIEW

**Comment by benma** [comment]
changelog

**Review by benma — COMMENTED** [review]
utACK - @NickeZ pls double check, is pause_clock ok in all cases?

**Comment by asi345** [comment]
Changelog is already updated in the previous commit, should I also update it here?

**Comment by benma** [comment]
> Changelog is already updated in the previous commit, should I also update it here?

I had already deleted it :P I looked at the wrong branch and didn't see there was already an entry. No need for a second one of course.

**Review by NickeZ — APPROVED** [review]
LGTM

Yes, I think it is appropriate to turn of the clock always when you return `false`.

**Pull request merged**
